import "./globals.css";
import { Nunito } from "next/font/google";
import Navbar from "../components/navbar/navbar";

export const metadata = {
  title: "AirBnB",
  description: "Generated by AirBnB",
};

const fonts = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
